"""restructure scan sessions to span whole invoice

Revision ID: 084e9f9cc1a8
Revises: ccd24096fc08
Create Date: 2026-08-13 17:03:30.872219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084e9f9cc1a8'
down_revision: Union[str, None] = 'ccd24096fc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM strip_scan_records")
    op.execute("DELETE FROM scan_sessions")
    op.add_column('scan_sessions', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.drop_constraint('scan_sessions_invoice_line_item_id_fkey', 'scan_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'scan_sessions', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('scan_sessions', 'expected_qty')
    op.drop_column('scan_sessions', 'invoice_line_item_id')
    op.drop_column('scan_sessions', 'product_name')
    op.drop_column('scan_sessions', 'batch_no_expected')
    op.drop_column('scan_sessions', 'scanned_qty')
    op.drop_column('strip_scan_records', 'batch_mismatch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strip_scan_records', sa.Column('batch_mismatch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scan_sessions', sa.Column('scanned_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scan_sessions', sa.Column('batch_no_expected', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('scan_sessions', sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('scan_sessions', sa.Column('invoice_line_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scan_sessions', sa.Column('expected_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scan_sessions', type_='foreignkey')
    op.create_foreign_key('scan_sessions_invoice_line_item_id_fkey', 'scan_sessions', 'invoice_line_items', ['invoice_line_item_id'], ['id'])
    op.drop_column('scan_sessions', 'invoice_id')
    # ### end Alembic commands ###
