"""add product inventory fields

Revision ID: 2f909fd8921b
Revises: 98db0e07399a
Create Date: 2026-07-14 06:15:36.531338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f909fd8921b'
down_revision: Union[str, None] = '98db0e07399a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # reorder_level is NOT NULL with a server_default since products may
    # already exist — a Python-side model default only applies to new
    # inserts, existing rows need a real value written at migration time
    # (same lesson learned from the visibility migration).
    op.add_column('products', sa.Column('reorder_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('rack_place', sa.String(length=100), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rack_place')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'batch_number')
    op.drop_column('products', 'reorder_level')
    # ### end Alembic commands ###
