"""add attempts_taken to strip scan records

Revision ID: 7a795e80d20a
Revises: a3f2ce0a9065
Create Date: 2026-08-14 10:47:30.822572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a795e80d20a'
down_revision: Union[str, None] = 'a3f2ce0a9065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strip_scan_records', sa.Column('attempts_taken', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strip_scan_records', 'attempts_taken')
    # ### end Alembic commands ###
