"""add scanned_by to strip scan records, share sessions per invoice

Revision ID: a3f2ce0a9065
Revises: 084e9f9cc1a8
Create Date: 2026-08-13 19:19:35.244451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f2ce0a9065'
down_revision: Union[str, None] = '084e9f9cc1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strip_scan_records', sa.Column('scanned_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strip_scan_records', 'users', ['scanned_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strip_scan_records', type_='foreignkey')
    op.drop_column('strip_scan_records', 'scanned_by_id')
    # ### end Alembic commands ###
