"""add coupons and app_settings

Revision ID: b0d27b29867b
Revises: 86d47f8316c7
Create Date: 2026-07-13 13:52:57.172044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b0d27b29867b'
down_revision: Union[str, None] = '86d47f8316c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('cms', 'store', name='settingcategory'), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.Enum('percentage', 'flat', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    # create_type=False: this enum type already exists in the DB (created by
    # the initial migration for product_pricing/orders/banners) — Postgres
    # enum types are database-global, not per-table, so re-creating it here
    # would collide with the existing one. Note: create_type only works on
    # postgresql.ENUM specifically — the generic sa.Enum(..., create_type=False)
    # silently ignores the flag and still emits CREATE TYPE.
    sa.Column('channel', postgresql.ENUM('b2c', 'b2b_normal', 'b2b_advance', name='pricingchannel', create_type=False), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
