"""add invoice and stock verification tables

Revision ID: ccd24096fc08
Revises: e5a9c3d72f16
Create Date: 2026-08-13 14:08:11.043346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd24096fc08'
down_revision: Union[str, None] = 'e5a9c3d72f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('wholesaler_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.String(length=20), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('exp_date', sa.String(length=20), nullable=True),
    sa.Column('pack', sa.String(length=50), nullable=False),
    sa.Column('pack_type', sa.Enum('strip', 'bottle', 'unit', 'other', name='packtype'), nullable=False),
    sa.Column('tablets_per_strip', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('invoice_line_item_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('batch_no_expected', sa.String(length=100), nullable=True),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('scanned_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='scansessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_line_item_id'], ['invoice_line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strip_scan_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_medicine_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_batch_no', sa.String(length=100), nullable=True),
    sa.Column('extracted_mfg_date', sa.String(length=20), nullable=True),
    sa.Column('extracted_exp_date', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('ocr_status', sa.Enum('accepted', 'needs_retry', name='ocrstatus'), nullable=False),
    sa.Column('batch_mismatch', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strip_scan_records')
    op.drop_table('scan_sessions')
    op.drop_table('invoice_line_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
